services:
  app_a:
    build: .
    container_name: mc_app_a
    command: ["/opt/mission/app_a"]
    networks:
      mission_control_net:
        ipv4_address: 172.28.0.2
    environment:
      PEER_IP: "172.28.0.3"
    restart: "no"

  app_b:
    build: .
    container_name: mc_app_b
    command: ["/opt/mission/app_b"]
    networks:
      mission_control_net:
        ipv4_address: 172.28.0.3
    environment:
      PEER_IP: "172.28.0.2"
    depends_on:
      - app_a
    restart: "no"

  ebpf_loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
      args:
        WSL_FLAG: 1
    image: mission-control-loader:latest
    container_name: ebpf_loader
    privileged: true
    network_mode: host
    pid: host
    depends_on:
      - app_a
      - app_b
    volumes:
      - ./:/opt/mission
      - /sys/kernel/btf/vmlinux:/sys/kernel/btf/vmlinux:ro
      - /sys/fs/bpf:/sys/fs/bpf
      - /sys/kernel/debug:/sys/kernel/debug:ro
    restart: "no"

networks:
  mission_control_net:
    name: mission_control_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1